/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.hmsproject.Reservation;

/**
 *
 * @author samsung
 */
public class RoomImagePage extends javax.swing.JFrame {

    /**
     * Creates new form RoomImagePage
     */
    public RoomImagePage() {
        initComponents();
        setTitle("Room Page");
    }
   // RoomImage roomimage = new RoomImage();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stadardtwin_Button = new javax.swing.JButton();
        Deluxdouble_Button = new javax.swing.JButton();
        Standardfamily_Button = new javax.swing.JButton();
        Comportdouble_Button = new javax.swing.JButton();
        Deluxdoublecityview_Button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Stadardtwin_Button.setText("스탠다드트윈");
        Stadardtwin_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Stadardtwin_Button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Stadardtwin_Button.setPreferredSize(new java.awt.Dimension(395, 165));
        Stadardtwin_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stadardtwin_ButtonActionPerformed(evt);
            }
        });

        Deluxdouble_Button.setText("디럭스더블");
        Deluxdouble_Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Deluxdouble_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deluxdouble_ButtonActionPerformed(evt);
            }
        });

        Standardfamily_Button.setText("스탠다드패밀리트윈");
        Standardfamily_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Standardfamily_ButtonActionPerformed(evt);
            }
        });

        Comportdouble_Button.setText("컴포트더블룸");
        Comportdouble_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comportdouble_ButtonActionPerformed(evt);
            }
        });

        Deluxdoublecityview_Button.setText("디럭스더블시티뷰");
        Deluxdoublecityview_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deluxdoublecityview_ButtonActionPerformed(evt);
            }
        });

        jButton2.setText("뒤로가기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Deluxdoublecityview_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Standardfamily_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Stadardtwin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Comportdouble_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deluxdouble_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(14, 14, 14)
                        .addComponent(Stadardtwin_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(Standardfamily_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Deluxdoublecityview_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Deluxdouble_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Comportdouble_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Stadardtwin_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stadardtwin_ButtonActionPerformed
        // TODO add your handling code here:
        ReservationPage1 reservationpage = new ReservationPage1();
        reservationpage.setVisible(true);
    }//GEN-LAST:event_Stadardtwin_ButtonActionPerformed

    private void Deluxdouble_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deluxdouble_ButtonActionPerformed
        // TODO add your handling code here:
        ReservationPage2 reservationpage = new ReservationPage2();
        reservationpage.setVisible(true);
    }//GEN-LAST:event_Deluxdouble_ButtonActionPerformed

    private void Standardfamily_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Standardfamily_ButtonActionPerformed
        // TODO add your handling code here:
        ReservationPage3 reservationpage = new ReservationPage3();
        reservationpage.setVisible(true);
    }//GEN-LAST:event_Standardfamily_ButtonActionPerformed

    private void Comportdouble_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comportdouble_ButtonActionPerformed
        // TODO add your handling code here:
        ReservationPage4 reservationpage = new ReservationPage4();
        reservationpage.setVisible(true);
    }//GEN-LAST:event_Comportdouble_ButtonActionPerformed

    private void Deluxdoublecityview_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deluxdoublecityview_ButtonActionPerformed
        // TODO add your handling code here:
        ReservationPage5 reservationpage = new ReservationPage5();
        reservationpage.setVisible(true);
    }//GEN-LAST:event_Deluxdoublecityview_ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomImagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomImagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomImagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomImagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomImagePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comportdouble_Button;
    private javax.swing.JButton Deluxdouble_Button;
    private javax.swing.JButton Deluxdoublecityview_Button;
    private javax.swing.JButton Stadardtwin_Button;
    private javax.swing.JButton Standardfamily_Button;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
