/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.hmsproject.Service.RoomService;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class RoomservicePage extends javax.swing.JFrame {

    /**
     * Creates new form RoomServicePage
     */
    public RoomservicePage() {
        initComponents();
        setTitle("RoomServicePage");
        try (FileReader r = new FileReader("Reservation.txt")) {
            BufferedReader reader = new BufferedReader(r);
            String ar = null;
            String[] Arr;

            while ((ar = reader.readLine()) != null) {
                Arr = ar.split("/");
                jComboBox3.addItem("" + Arr[0]);
            }
            r.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Room_Food = new javax.swing.JComboBox<>();
        Room_Beer = new javax.swing.JComboBox<>();
        Room_Desert = new javax.swing.JComboBox<>();
        OrderBut = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Oderdelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("룸서비스");

        jButton1.setText("뒤로가기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("음식 :");

        jLabel3.setText("주류 :");

        jLabel4.setText("디저트 :");

        Room_Food.setMaximumRowCount(20);
        Room_Food.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "한식(불고기)/7000", "중식(짜장면)/8000", "양식(파스타)/8000", "일식(라멘,스시)/10000", "선택안함/0" }));
        Room_Food.setPreferredSize(new java.awt.Dimension(500, 23));
        Room_Food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_FoodActionPerformed(evt);
            }
        });

        Room_Beer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "맥주/4500", "생맥주/5000", "칵테일/8000", "막걸리/4500", "보드카/10000", "선택안함/0" }));
        Room_Beer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_BeerActionPerformed(evt);
            }
        });

        Room_Desert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dessert", "케이크/4500", "마카롱/2000", "샌드위치/3000", "아이스크림/2000", "선택안함/0" }));
        Room_Desert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room_DesertActionPerformed(evt);
            }
        });

        OrderBut.setText("주문하기");
        OrderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButActionPerformed(evt);
            }
        });

        jButton3.setText("주문수정하기");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Oderdelete.setText("주문취소하기");
        Oderdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OderdeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("서비스 주문자 :");

        jLabel6.setText("서비스 이용 객실 : ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name" }));

        jButton2.setText("검색하기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(Oderdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Room_Beer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Room_Food, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Room_Desert, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(OrderBut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Room_Food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Room_Beer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderBut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Desert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Oderdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    boolean check=true;
    private void OrderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButActionPerformed
        // TODO add your handling code here:
        String customer = jTextField1.getText();
        String room = jTextField2.getText();
        String food = Room_Food.getSelectedItem().toString();
        String beer = Room_Beer.getSelectedItem().toString();
        String desert = Room_Desert.getSelectedItem().toString();

        int foodmoney = 0;//룸서비스 음식값
        int beermoney = 0;//룸서비스 주류값
        int desertmoney = 0;//룸서비스 디저트값

        ArrayList<String> tempArray = new ArrayList<>();

        try {
            try (FileReader fr = new FileReader("Reservation.txt")) {
                Scanner reader = new Scanner(fr);
                String line = null;
                String[] lineArr;

                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split("/");
                    if (Room_Food.getSelectedItem().equals("한식(불고기)/7000")) {
                        foodmoney = 7000;
                    }
                    if (Room_Food.getSelectedItem().equals("중식(짜장면)/8000")) {
                        foodmoney = 8000;
                    }
                    if (Room_Food.getSelectedItem().equals("양식(파스타)/8000")) {
                        foodmoney = 8000;
                    }
                    if (Room_Food.getSelectedItem().equals("일식(라멘,스시)/10000")) {
                        foodmoney = 10000;
                    }
                    if (Room_Food.getSelectedItem().equals("선택안함/0")) {
                        foodmoney = 0;
                    }
                    if (Room_Beer.getSelectedItem().equals("맥주/4500")) {
                        beermoney = 4500;
                    }
                    if (Room_Beer.getSelectedItem().equals("생맥주/5000")) {
                        beermoney = 5000;
                    }
                    if (Room_Beer.getSelectedItem().equals("칵테일/8000")) {
                        beermoney = 4500;
                    }
                    if (Room_Beer.getSelectedItem().equals("막걸리/4500")) {
                        beermoney = 4500;
                    }
                    if (Room_Beer.getSelectedItem().equals("보드카/10000")) {
                        beermoney = 10000;
                    }
                    if (Room_Beer.getSelectedItem().equals("선택안함/0")) {
                        beermoney = 0;
                    }
                    if (Room_Desert.getSelectedItem().equals("케이크/4500")) {
                        desertmoney = 4500;
                    }
                    if (Room_Desert.getSelectedItem().equals("마카롱/2000")) {
                        desertmoney = 2000;
                    }
                    if (Room_Desert.getSelectedItem().equals("샌드위치/3000")) {
                        desertmoney = 3000;
                    }
                    if (Room_Desert.getSelectedItem().equals("아이스크림/2000")) {
                        desertmoney = 2000;
                    }
                    if (Room_Desert.getSelectedItem().equals("선택안함/0")) {
                        desertmoney = 0;
                    } else {
                        tempArray.add(line);
                    }
                }
                fr.close();
            } catch (Exception e) {
            }

            int allmoney = foodmoney + beermoney + desertmoney;//룸서비스 총 비용
            String to = Integer.toString(allmoney);
            
            File ffff = new File("RoomService.txt");
            
            
            try {
                File fi = new File("Reservation.txt");
                FileReader f;
                f = new FileReader(fi);
                BufferedReader reader = new BufferedReader(f);
                String line = null;
                String[] arr;
                while ((line = reader.readLine()) != null) {
                    arr = line.split("/");
                    if (arr[9].equals(room)) {
                        check = true;
                        break;
                    }
                }
                if (check == true) {
                    JOptionPane.showMessageDialog(null, "룸서비스 주문이 접수되었습니다!");
                    FileWriter writer;
                    String s = "/";

                    writer = new FileWriter(ffff, true);
                    writer.write(customer);
                    writer.write(s);
                    writer.write(room);
                    writer.write(s);
                    writer.write(food);
                    writer.write(s);
                    writer.write(beer);
                    writer.write(s);
                    writer.write(desert);
                    writer.write(s);
                    writer.write(to);
                    writer.flush();// 출력은 버퍼에 쌓여있기에 쌓인 버퍼를 목적지로 보내줌
                    writer.close();
                }

            } catch (IOException e) {
                System.out.println("오류발생");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_OrderButActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RoomserviceEditPage ode = new RoomserviceEditPage();
        ode.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OderdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OderdeleteActionPerformed
        RoomserviceDelete sd = new RoomserviceDelete();
        sd.setVisible(true);
    }//GEN-LAST:event_OderdeleteActionPerformed

    private void Room_BeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_BeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_BeerActionPerformed

    private void Room_DesertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_DesertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_DesertActionPerformed

    private void Room_FoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_FoodActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Room_FoodActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String str = jComboBox3.getSelectedItem().toString();
        try {
            String s;
            String[] array;
            BufferedReader bo = new BufferedReader(new FileReader("Reservation.txt"));
            while ((s = bo.readLine()) != null) {
                array = s.split("/");
                if (str.equals(array[0])) {
                    jTextField1.setText("" + array[0]);
                    jTextField2.setText("" + array[9]);
                }
            }
            bo.close();
        } catch (IOException E10) {
            E10.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomservicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomservicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomservicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomservicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomservicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Oderdelete;
    private javax.swing.JButton OrderBut;
    private javax.swing.JComboBox<String> Room_Beer;
    private javax.swing.JComboBox<String> Room_Desert;
    private javax.swing.JComboBox<String> Room_Food;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
