/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.hmsproject.CheckOut;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class CheckOutPage extends javax.swing.JFrame {

    /**
     * Creates new form CheckOutPage
     */
    public CheckOutPage() {
        initComponents();
        setTitle("CheckOut Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckOutTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bill1 = new javax.swing.JTextField();
        bill2 = new javax.swing.JTextField();
        bill4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Customername = new javax.swing.JTextField();
        Roomnum = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        bill3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1.setText("체크아웃");

        jLabel2.setText("퇴실시간");

        jButton1.setText("입력");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("고객 청구서");

        bill1.setText("1. 기본객실요금 :");
        bill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill1ActionPerformed(evt);
            }
        });

        bill2.setText("2. 서비스 이용 요금 :");
        bill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill2ActionPerformed(evt);
            }
        });

        bill4.setText("추가요금 :");
        bill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill4ActionPerformed(evt);
            }
        });

        jLabel5.setText("고객 이름 ");

        jLabel6.setText("객실 번호 ");

        Customername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomernameActionPerformed(evt);
            }
        });

        jButton2.setText("뒤로가기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill3ActionPerformed(evt);
            }
        });

        jLabel4.setText("총 금액 ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Customername, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bill3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bill2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bill4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(Customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bill4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill1ActionPerformed
    boolean check;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String str1 = Customername.getText();
        String str2 = Roomnum.getText();
        String choutime = CheckOutTime.getText();

        String asdf;
        asdf = CheckOutTime.getText();

        int checkouttime = Integer.parseInt(asdf);

        if (checkouttime > 11) {
            checkouttime = checkouttime - 11;
        } else {
            checkouttime = 0;
        }
        bill4.setText("추가요금 : " + checkouttime * 3000);

        int servicevalue; // 룸서비스와 레스토랑 서비즈 비용 합

        try {
            try (FileReader fr = new FileReader("Reservation.txt")) {
                FileReader fi;
                fi = new FileReader("Reservation.txt");
                BufferedReader reer = new BufferedReader(fi);
                String ne = null;
                String[] r;

                while ((ne = reer.readLine()) != null) {
                    r = ne.split("/");
                    int num2 = Integer.parseInt(r[9]);
                    int roomprice = 0;
                    if (num2 < 21) {
                        roomprice = 80000;
                        bill1.setText("1. 기본객실요금 : " + roomprice);
                    } else if (num2 > 20 && num2 < 41) {
                        roomprice = 85000;
                        bill1.setText("1. 기본객실요금 : " + roomprice);
                    } else if (num2 > 40 && num2 < 61) {
                        roomprice = 90000;
                        bill1.setText("1. 기본객실요금 : " + roomprice);
                    } else if (num2 > 60 && num2 < 81) {
                        roomprice = 95000;
                        bill1.setText("1. 기본객실요금 : " + roomprice);
                    } else if (num2 > 80 && num2 < 101) {
                        roomprice = 100000;
                    }
                    int moo = roomprice + checkouttime;

                    try {
                        File fe = new File("RoomService.txt");//룸 서비스텍스트 파일 불러옴
                        FileReader fo;
                        fo = new FileReader("RoomService.txt");
                        BufferedReader reader = new BufferedReader(fo);
                        String line = null;
                        String[] arr;

                        File ff = new File("RestaurantService.txt");//레스토랑서비스 파일 불러옴
                        FileReader fw;
                        fw = new FileReader("RestaurantService.txt");
                        BufferedReader rea = new BufferedReader(fw);
                        String lin = null;
                        String[] ar;

                        while ((line = reader.readLine()) != null && (lin = rea.readLine()) != null) {
                            arr = line.split("/");
                            ar = lin.split("/");

                            int ap = Integer.parseInt(arr[8]);
                            int ad = Integer.parseInt(ar[8]);

                            servicevalue = ap + ad;
                            bill2.setText("2. 서비스 이용 요금 : " + servicevalue);
                            int money = moo + servicevalue;
                            String g = Integer.toString(money);
                            bill3.setText(g);
                        }

                    } catch (Exception e) {
                    }
                }
                String m = bill3.getText();
                Scanner reader = new Scanner(fr);
                String line = null;
                String[] lineArr;
                String ls = "";
                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split("/");

                    if (!lineArr[0].equals(str1) || !lineArr[9].equals(str2)) {
                        check = false;
                    }
                    if (lineArr[0].equals(str1) && lineArr[9].equals(str2)) {
                        ls += line;
                        check = true;
                        break;
                    }
                }
                if (check == false) {
                    JOptionPane.showMessageDialog(null, "체크아웃이 취소 되었습니다");
                }
                if (check == true) {
                    File file = new File("CheckOut.txt");
                    FileWriter write = null;
                    String d = "\n";
                    write = new FileWriter(file, true);
                    write.write(ls);
                    write.write("/");
                    write.write(choutime);
                    write.write("/");
                    write.write(m);
                    write.write(d);
                    write.flush();
                    JOptionPane.showMessageDialog(null, "체크아웃이 완료 되었습니다");
                }
                fr.close();
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void bill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill4ActionPerformed

    private void CustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomernameActionPerformed

    private void bill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheckOutTime;
    private javax.swing.JTextField Customername;
    private javax.swing.JTextField Roomnum;
    private javax.swing.JTextField bill1;
    private javax.swing.JTextField bill2;
    private javax.swing.JTextField bill3;
    private javax.swing.JTextField bill4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
