/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.oop2.hmsproject.CheckOut;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMSUNG_
 */
public class Payment_Page extends javax.swing.JFrame {

    /**
     * Creates new form Payment_Page
     */
    public Payment_Page() {
        initComponents();

        try (FileReader r = new FileReader("Reservation.txt")) {
            BufferedReader reader = new BufferedReader(r);
            String ar;
            String[] Arr;

            while ((ar = reader.readLine()) != null) {
                Arr = ar.split("/");
                Roomnumber_combo.addItem("" + Arr[9]);
            }
            r.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roomchargeText = new javax.swing.JTextField();
        resText = new javax.swing.JTextField();
        serviceText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalpayText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Payment_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        customerPayText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Roomnumber_combo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("결제");

        jLabel2.setText("객실료");

        jLabel3.setText("레스토랑");

        jLabel4.setText("룸서비스");

        roomchargeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomchargeTextActionPerformed(evt);
            }
        });

        serviceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceTextActionPerformed(evt);
            }
        });

        jLabel5.setText("총 지불할 금액");

        totalpayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpayTextActionPerformed(evt);
            }
        });

        jButton1.setText("뒤로가기");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Payment_Button.setText("결제하기");
        Payment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("고객이 지불한 금액");

        jLabel7.setText("객실 ");

        Roomnumber_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RoomNumber" }));
        Roomnumber_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Roomnumber_comboActionPerformed(evt);
            }
        });

        jButton2.setText("검색");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 408, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalpayText, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(serviceText)
                                    .addComponent(resText)
                                    .addComponent(roomchargeText)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Roomnumber_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerPayText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Payment_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Roomnumber_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(roomchargeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(resText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(serviceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(totalpayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Payment_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalpayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpayTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Payment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_ButtonActionPerformed
        // TODO add your handling code here:
        String totalpay = totalpayText.getText();
        int n = Integer.parseInt(totalpay);
        String customerpay = customerPayText.getText();
        int n1 = Integer.parseInt(customerpay);
        String rn = Roomnumber_combo.getSelectedItem().toString();
        if (n == n1) {
            JOptionPane.showMessageDialog(null, "결제가 완료 되었습니다.");

            String roomch = roomchargeText.getText();
            String res = resText.getText();
            String sev = serviceText.getText();

            String tt = totalpayText.getText();

            try {
                File file = new File("Payment.txt");
                FileWriter writer = null;
                String s = "/";

                writer = new FileWriter(file, true);
                writer.write(roomch);
                writer.write(s);//방 가격 
                writer.write(res);
                writer.write(s); //레스토랑
                writer.write(sev);
                writer.write(s); //룸서비스금액
                writer.write(tt); //총금액
                writer.flush();// 출력은 버퍼에 쌓여있기에 쌓인 버퍼를 목적지로 보내줌
                writer.close();
            } catch (IOException e) {
                System.out.println("오류발생");
            }
        } else {
            JOptionPane.showMessageDialog(null, "결제해야할 금액과 지불할 금액이 다릅니다.");
        }

        FileWriter fw;
        try (FileReader fr = new FileReader("Reservation.txt")) {
            BufferedReader reader = new BufferedReader(fr);
            String line;
            String[] lineArr;
            String asd = "";
            while ((line = reader.readLine()) != null) {
                lineArr = line.split("/");
                if (!lineArr[9].equals(rn)) {
                    asd += line + "\r\n";
                }
            }
            fw = new FileWriter("Reservation.txt");
            fw.write(asd);
            fw.close();
            fr.close();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_Payment_ButtonActionPerformed

    private void roomchargeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomchargeTextActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_roomchargeTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String rn = Roomnumber_combo.getSelectedItem().toString();

        String billroomcharge = roomchargeText.getText();
        String billres = resText.getText();
        String billservice = serviceText.getText();

        try {
            try (FileReader fr = new FileReader("RoomPrice.txt")) {
                Scanner reader = new Scanner(fr);
                String line = null;
                String[] lineArr;

                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split("/");

                    roomchargeText.setText(lineArr[1]);

                }
                fr.close();
            } catch (Exception e) {
            }

            try (FileReader fr = new FileReader("RestaurantService.txt")) {
                Scanner reader = new Scanner(fr);
                String line = null;
                String[] lineArr;
                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split("/");
                    resText.setText(lineArr[8]);
                }
                fr.close();
            } catch (Exception e) {
            }

            try (FileReader fr = new FileReader("RoomService.txt")) {
                Scanner reader = new Scanner(fr);
                String line = null;
                String[] lineArr;

                while ((line = reader.nextLine()) != null) {
                    lineArr = line.split("/");
                    serviceText.setText(lineArr[8]);
                }
                fr.close();
            } catch (Exception e) {
            }

            int roomch = Integer.parseInt(billroomcharge);
            int res = Integer.parseInt(billres);
            int sev = Integer.parseInt(billservice);

            int total = 0;
            total = roomch + res + sev;
            totalpayText.setText("" + total);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Roomnumber_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Roomnumber_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Roomnumber_comboActionPerformed

    private void serviceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Payment_Button;
    private javax.swing.JComboBox<String> Roomnumber_combo;
    private javax.swing.JTextField customerPayText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField resText;
    private javax.swing.JTextField roomchargeText;
    private javax.swing.JTextField serviceText;
    private javax.swing.JTextField totalpayText;
    // End of variables declaration//GEN-END:variables
}
